### ISSUE TITLE
datetime

### ISSUE THREAD

**Issue by yu-kod** [c0a21109/ProjExD#1]
https://github.com/c0a21109/ProjExD/blob/f4ccfcec0a095f6b6c30891b3b032a99661d732d/ex01/alphabet.py#L65

datetimeではなくtimeを使用すれば最後の変換が楽になります。

**Comment by c0a21109** [comment]
ありがとうございます。___φ(｡_｡*)ﾒﾓﾒﾓ
どんな様にしたらいいのでしょうか;;

p.s. できました
