### ISSUE TITLE
これはデバッグ用？

### ISSUE THREAD

**Issue by c0a21095** [c0a21109/ProjExD#7]
このprint文はデバッグ用の文章でしょうか？
コメントを記載するなど、用途を明示したほうかいいと思います。

**Comment by c0a21109** [comment]
でバック用です

**Comment by c0a21095** [comment]
https://github.com/c0a21109/ProjExD/blob/119a80e23c3b68584714d759e8b93f5733e93441/ex03/ex03.py#L121
場所が抜けていました。ここです。
